const cursos={enfermagem:{nome:'Enfermagem',mensalidade:1307.19,parcelas:6,cargaHoraria:4000,bolsa:15,pontualidade:5},fonoaudiologia:{nome:'Fonoaudiologia',mensalidade:1561.66,parcelas:6,cargaHoraria:3600,bolsa:10,pontualidade:5},psicologia:{nome:'Psicologia',mensalidade:1420.50,parcelas:6,cargaHoraria:4000,bolsa:12,pontualidade:5},medicinaVeterinaria:{nome:'Medicina Veterinária',mensalidade:2890.00,parcelas:6,cargaHoraria:4500,bolsa:8,pontualidade:7},odontologia:{nome:'Odontologia',mensalidade:3200.00,parcelas:6,cargaHoraria:4800,bolsa:10,pontualidade:5},nutricao:{nome:'Nutrição',mensalidade:1250.00,parcelas:6,cargaHoraria:3800,bolsa:15,pontualidade:5}};
const selectCurso=document.getElementById('selectCurso');
const inputChTotalCurso=document.getElementById('chTotalCurso');
const inputChDisciplina=document.getElementById('chDisciplina');
const inputQtdParcelas=document.getElementById('qtdParcelas');
const inputMensalidadeIntegral=document.getElementById('mensalidadeIntegral');
const inputBolsaIncentivo=document.getElementById('bolsaIncentivo');
const inputDescontoPontualidade=document.getElementById('descontoPontualidade');
const btnCalcular=document.getElementById('btnCalcular');
const btnLimpar=document.getElementById('btnLimpar');
const formCalculadora=document.getElementById('formCalculadora');
const mensagemErro=document.getElementById('mensagemErro');
const cardResultado=document.getElementById('cardResultado');
const badgeStatus=document.getElementById('badgeStatus');
const spinnerLoading=document.getElementById('spinnerLoading');
const iconCalcular=document.getElementById('iconCalcular');
const resCurso=document.getElementById('resCurso');
const resChCurso=document.getElementById('resChCurso');
const resChDisciplina=document.getElementById('resChDisciplina');
const resValorHora=document.getElementById('resValorHora');
const resMensalidadeIntegral=document.getElementById('resMensalidadeIntegral');
const resValorBolsa=document.getElementById('resValorBolsa');
const resMensalidadeAposBolsa=document.getElementById('resMensalidadeAposBolsa');
const resDescontoPontualidade=document.getElementById('resDescontoPontualidade');
const resValorLiquido=document.getElementById('resValorLiquido');
const resValorTotalDisciplina=document.getElementById('resValorTotalDisciplina');
const resNumParcelas=document.getElementById('resNumParcelas');
const resValorPorParcela=document.getElementById('resValorPorParcela');
const campos=[inputChTotalCurso,inputChDisciplina,inputQtdParcelas,inputMensalidadeIntegral,inputBolsaIncentivo,inputDescontoPontualidade];
document.addEventListener('DOMContentLoaded',inicializarAplicacao);
function inicializarAplicacao(){selectCurso.addEventListener('change',tratarSelecaoCurso);btnCalcular.addEventListener('click',executarFluxoCalculo);btnLimpar.addEventListener('click',limparFormulario);campos.forEach(campo=>{campo.addEventListener('input',tratarAlteracaoCampo);campo.addEventListener('change',tratarAlteracaoCampo)});resetarDemonstrativoVisual()}
function tratarSelecaoCurso(){const cursoChave=selectCurso.value;const cursoDados=cursos[cursoChave];if(!cursoDados){limparCamposCurso();resetarDemonstrativoVisual();return}inputChTotalCurso.value=cursoDados.cargaHoraria;inputChDisciplina.value='';inputQtdParcelas.value=cursoDados.parcelas;inputMensalidadeIntegral.value=cursoDados.mensalidade;inputBolsaIncentivo.value=cursoDados.bolsa;inputDescontoPontualidade.value=cursoDados.pontualidade;inputChDisciplina.focus();if(inputChDisciplina.value){executarFluxoCalculo(false)}else{resetarDemonstrativoVisual()}}
function tratarAlteracaoCampo(){limparMensagemErro();if(!selectCurso.value){resetarDemonstrativoVisual();return}const camposPreenchidos=campos.every(campo=>campo.value!=='');if(camposPreenchidos){executarFluxoCalculo(false)}else{resetarDemonstrativoVisual()}}
function executarFluxoCalculo(exibirLoading=true){const validacao=validarFormulario();if(!validacao.valido){mensagemErro.textContent=validacao.mensagem;mensagemErro.classList.remove('d-none');resetarDemonstrativoVisual();return}mensagemErro.classList.add('d-none');if(exibirLoading){mostrarLoading(true);window.setTimeout(()=>{executarCalculosReais();mostrarLoading(false)},350);return}executarCalculosReais()}
function validarFormulario(){const dados={curso:selectCurso.value,chTotalCurso:Number(inputChTotalCurso.value),chDisciplina:Number(inputChDisciplina.value),qtdParcelas:Number(inputQtdParcelas.value),mensalidadeIntegral:Number(inputMensalidadeIntegral.value),bolsaIncentivo:Number(inputBolsaIncentivo.value),descontoPontualidade:Number(inputDescontoPontualidade.value)};if(!dados.curso){return{valido:false,mensagem:'Selecione um curso para iniciar o cálculo.'}}if(!Number.isFinite(dados.chTotalCurso)||dados.chTotalCurso<=0){return{valido:false,mensagem:'Informe a carga horária total do curso.'}}if(!Number.isFinite(dados.chDisciplina)||dados.chDisciplina<=0){return{valido:false,mensagem:'Informe a carga horária da disciplina.'}}if(!Number.isFinite(dados.qtdParcelas)||dados.qtdParcelas<=0){return{valido:false,mensagem:'Informe a quantidade de parcelas.'}}if(!Number.isFinite(dados.mensalidadeIntegral)||dados.mensalidadeIntegral<0){return{valido:false,mensagem:'Informe a mensalidade integral corretamente.'}}if(!Number.isFinite(dados.bolsaIncentivo)||dados.bolsaIncentivo<0||dados.bolsaIncentivo>100){return{valido:false,mensagem:'A bolsa de incentivo deve estar entre 0% e 100%.'}}if(!Number.isFinite(dados.descontoPontualidade)||dados.descontoPontualidade<0||dados.descontoPontualidade>100){return{valido:false,mensagem:'O desconto de pontualidade deve estar entre 0% e 100%.'}}return{valido:true}}
function executarCalculosReais(){const nomeCurso=selectCurso.options[selectCurso.selectedIndex]?.text||'Curso';const chTotalCurso=Number(inputChTotalCurso.value)||0;const chDisciplina=Number(inputChDisciplina.value)||0;const qtdParcelas=Number(inputQtdParcelas.value)||1;const mensalidadeIntegral=Number(inputMensalidadeIntegral.value)||0;const porcBolsa=Number(inputBolsaIncentivo.value)||0;const porcPontualidade=Number(inputDescontoPontualidade.value)||0;const valorHora=chTotalCurso>0?mensalidadeIntegral/chTotalCurso:0;const valorDisciplina=valorHora*chDisciplina;const valorBolsa=valorDisciplina*(porcBolsa/100);const valorAposBolsa=valorDisciplina-valorBolsa;const valorDescontoPontualidade=valorAposBolsa*(porcPontualidade/100);const valorLiquido=valorAposBolsa-valorDescontoPontualidade;const valorPorParcela=qtdParcelas>0?valorLiquido/qtdParcelas:valorLiquido;resCurso.textContent=nomeCurso;resChCurso.textContent=`${chTotalCurso} h`;resChDisciplina.textContent=`${chDisciplina} h`;resValorHora.textContent=formatarMoeda(valorHora);resMensalidadeIntegral.textContent=formatarMoeda(valorDisciplina);resValorBolsa.textContent=`- ${formatarMoeda(valorBolsa)} (${porcBolsa.toFixed(1)}%)`;resMensalidadeAposBolsa.textContent=formatarMoeda(valorAposBolsa);resDescontoPontualidade.textContent=`- ${formatarMoeda(valorDescontoPontualidade)} (${porcPontualidade.toFixed(1)}%)`;resValorLiquido.textContent=formatarMoeda(valorLiquido);resValorTotalDisciplina.textContent=formatarMoeda(valorLiquido);resNumParcelas.textContent=qtdParcelas;resValorPorParcela.textContent=formatarMoeda(valorPorParcela);cardResultado.classList.add('ativo');cardResultado.classList.remove('opacity-75');badgeStatus.textContent='Calculado';badgeStatus.className='badge bg-success px-2 py-1'}
function formatarMoeda(valor){return valor.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function mostrarLoading(estado){spinnerLoading.classList.toggle('d-none',!estado);iconCalcular.classList.toggle('d-none',estado);btnCalcular.disabled=estado}
function resetarDemonstrativoVisual(){cardResultado.classList.remove('ativo');cardResultado.classList.add('opacity-75');badgeStatus.textContent='Aguardando Cálculo';badgeStatus.className='badge bg-secondary-subtle text-secondary px-2 py-1';const elementosRes=[resCurso,resChCurso,resChDisciplina,resValorHora,resMensalidadeIntegral,resValorBolsa,resMensalidadeAposBolsa,resDescontoPontualidade,resValorLiquido,resValorTotalDisciplina,resNumParcelas,resValorPorParcela];elementosRes.forEach(elemento=>{elemento.textContent='-'})}
function limparCamposCurso(){inputChTotalCurso.value='';inputChDisciplina.value='';inputQtdParcelas.value='';inputMensalidadeIntegral.value='';inputBolsaIncentivo.value='';inputDescontoPontualidade.value=''}
function limparFormulario(){formCalculadora.reset();limparCamposCurso();limparMensagemErro();resetarDemonstrativoVisual()}
function limparMensagemErro(){mensagemErro.textContent='';mensagemErro.classList.add('d-none')}
